version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: launchpad
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  hardhat:
    build:
      context: ./contracts
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    volumes:
      - ./contracts:/app
      - contracts_cache:/app/cache
      - contracts_artifacts:/app/artifacts
    command: npx hardhat node --hostname 0.0.0.0

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/launchpad?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - RPC_URL=http://hardhat:8545
      - JWT_SECRET=your-secret-key
    depends_on:
      - postgres
      - redis
      - hardhat
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NEXT_PUBLIC_RPC_URL=http://localhost:8545
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
  contracts_cache:
  contracts_artifacts: